### PR TITLE
Add vault contract

### PR DESCRIPTION
**Pull request by HulkChow**

### CODE REVIEW

**Review by bbyte837 — APPROVED** [review]
ok

**Review by bbyte837 — APPROVED** [review]
ok

**Review by RichardBrown123go — COMMENTED** [review]
Thanks for updating.
A bit suggestion in code review.

**Review by RichardBrown123go — CHANGES_REQUESTED** [review]
Nice work.
A little question here.

**Review by RichardBrown123go — APPROVED** [review]

**Pull request merged**
